import json
import urllib.parse
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import RedirectResponse
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build

from app.core.config import settings
from app.core.database import get_database
from app.core.security import create_access_token

router = APIRouter()

# In-memory store for PKCE code_verifiers keyed by OAuth state.
# In production, use a database or Redis. This works fine for single-server dev.
_oauth_states: dict = {}

# Client config mapping settings properties into standard client secrets format
def get_client_config():
    return {
        "web": {
            "client_id": settings.GOOGLE_CLIENT_ID,
            "client_secret": settings.GOOGLE_CLIENT_SECRET,
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "redirect_uris": [settings.GOOGLE_REDIRECT_URI],
        }
    }

# Scopes for openid profile info, reading and sending gmail
SCOPES = [
    "openid",
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
    "https://www.googleapis.com/auth/gmail.readonly",
    "https://www.googleapis.com/auth/gmail.send",
    "https://www.googleapis.com/auth/calendar",
]

@router.get("/login", summary="Initiate Google OAuth Flow")
async def login():
    if settings.GOOGLE_CLIENT_ID == "mock-client-id" or settings.GOOGLE_CLIENT_SECRET == "mock-client-secret":
        # Fallback helper for local dev without credentials
        mock_payload = {
            "id": "usr-mock-google-100",
            "email": "bharath@example.com",
            "name": "Bharath",
            "picture": ""
        }
        local_jwt = create_access_token(data=mock_payload)
        encoded_user = urllib.parse.quote(json.dumps(mock_payload))
        return RedirectResponse(f"{settings.FRONTEND_URL}/login-success?token={local_jwt}&user={encoded_user}")

    try:
        flow = Flow.from_client_config(
            client_config=get_client_config(),
            scopes=SCOPES,
            redirect_uri=settings.GOOGLE_REDIRECT_URI
        )
        authorization_url, state = flow.authorization_url(
            access_type="offline",
            include_granted_scopes="true",
            prompt="consent"
        )

        # Store the code_verifier generated by the Flow for PKCE in MongoDB
        # This makes it survive server restarts and multiple scaling workers.
        db = get_database()
        if db is not None:
            await db.oauth_states.insert_one({
                "state": state,
                "code_verifier": flow.code_verifier
            })
        else:
            _oauth_states[state] = {
                "code_verifier": flow.code_verifier,
            }

        return RedirectResponse(authorization_url)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"OAuth setup failure: {str(e)}"
        )

@router.get("/callback", summary="Google OAuth Callback Handler")
async def callback(code: str, state: Optional[str] = None):
    try:
        flow = Flow.from_client_config(
            client_config=get_client_config(),
            scopes=SCOPES,
            redirect_uri=settings.GOOGLE_REDIRECT_URI
        )

        # Restore the PKCE code_verifier from MongoDB
        code_verifier = None
        db = get_database()
        if db is not None and state:
            stored = await db.oauth_states.find_one_and_delete({"state": state})
            if stored:
                code_verifier = stored.get("code_verifier")
        
        # Fallback to in-memory store
        if not code_verifier and state and state in _oauth_states:
            stored = _oauth_states.pop(state)
            code_verifier = stored.get("code_verifier")

        if code_verifier:
            flow.code_verifier = code_verifier

        flow.fetch_token(code=code)
        credentials = flow.credentials

        user_info_service = build("oauth2", "v2", credentials=credentials)
        user_info = user_info_service.userinfo().get().execute()

        email = user_info.get("email")
        name = user_info.get("name")
        picture = user_info.get("picture")
        google_id = user_info.get("id")

        if not email:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Google account does not provide email."
            )

        # Persist user and credentials to MongoDB (non-fatal if DB is unavailable)
        try:
            db = get_database()
            if db is not None:
                # Prepare credential dict
                google_cred_dict = {
                    "token": credentials.token,
                    "token_uri": credentials.token_uri,
                    "client_id": credentials.client_id,
                    "client_secret": credentials.client_secret,
                    "scopes": list(credentials.scopes) if credentials.scopes else [],
                    "expiry": credentials.expiry.isoformat() if credentials.expiry else None
                }
                # Only overwrite refresh_token if Google returned it (usually on consent screen)
                if credentials.refresh_token:
                    google_cred_dict["refresh_token"] = credentials.refresh_token

                existing_user = await db.users.find_one({"email": email})
                if existing_user:
                    # Carry over old refresh token if not provided in this redirect
                    if "refresh_token" not in google_cred_dict and "google_credentials" in existing_user:
                        google_cred_dict["refresh_token"] = existing_user["google_credentials"].get("refresh_token")
                    
                    await db.users.update_one(
                        {"email": email},
                        {"$set": {
                            "name": name,
                            "picture": picture,
                            "google_credentials": google_cred_dict
                        }}
                    )
                else:
                    await db.users.update_one(
                        {"email": email},
                        {"$set": {
                            "_id": google_id,
                            "email": email,
                            "name": name,
                            "picture": picture,
                            "google_credentials": google_cred_dict
                        }},
                        upsert=True
                    )
        except Exception as db_err:
            print(f"Warning: Failed to persist user to MongoDB (login will still proceed): {db_err}")

        # Create session JWT for user
        token_payload = {
            "id": google_id or email,
            "email": email,
            "name": name,
            "picture": picture
        }
        local_jwt = create_access_token(data=token_payload)

        # Redirect to frontend dashboard success handler
        encoded_user = urllib.parse.quote(json.dumps(token_payload))
        frontend_url = f"{settings.FRONTEND_URL}/login-success?token={local_jwt}&user={encoded_user}"
        return RedirectResponse(frontend_url)

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"OAuth verification failure: {str(e)}"
        )
